// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Framework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UISomePanelFromResourcesData : Framework.UIPanelData
    {
    }
    
    public partial class UISomePanelFromResources : Framework.UIPanel
    {

        
        protected override void OnInit(Framework.IUIData uiData)
        {
            mData = uiData as UISomePanelFromResourcesData ?? new UISomePanelFromResourcesData();
            // please add init code here
            
            BtnCloseSelf.onClick.AddListener(() =>
            {
//                UIMgr.CloseAllPanel();

                UIKit.ClosePanel("resources://" + typeof(UISomePanelFromResources).Name);
            });
        }
        
        protected override void OnOpen(Framework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
